import { UNIT_TAGS } from "../core/constants.js";

/**
 * All battlefield units use the same normalized stat shape.
 */
export const UNIT_CATALOG = {
  grunt: {
    id: "grunt",
    name: "Grunt",
    family: UNIT_TAGS.INFANTRY,
    cost: 100,
    maxHealth: 18,
    attack: 10,
    armor: 1,
    movement: 4,
    minRange: 1,
    maxRange: 1,
    staminaMax: 4,
    ammoMax: 7,
    luck: 2,
    effectiveAgainstTags: [],
  },
  breaker: {
    id: "breaker",
    name: "Breaker",
    family: UNIT_TAGS.INFANTRY,
    cost: 250,
    maxHealth: 16,
    attack: 10,
    armor: 2,
    movement: 4,
    minRange: 1,
    maxRange: 1,
    staminaMax: 4,
    ammoMax: 5,
    luck: 3,
    effectiveAgainstTags: [UNIT_TAGS.VEHICLE],
  },
  longshot: {
    id: "longshot",
    name: "Longshot",
    family: UNIT_TAGS.INFANTRY,
    cost: 300,
    maxHealth: 14,
    attack: 10,
    armor: 0,
    movement: 3,
    minRange: 2,
    maxRange: 3,
    staminaMax: 3,
    ammoMax: 6,
    luck: 3,
    effectiveAgainstTags: [UNIT_TAGS.INFANTRY],
  },
  runner: {
    id: "runner",
    name: "Runner",
    family: UNIT_TAGS.VEHICLE,
    cost: 400,
    maxHealth: 20,
    attack: 11,
    armor: 5,
    movement: 6,
    minRange: 1,
    maxRange: 1,
    staminaMax: 6,
    ammoMax: 7,
    luck: 2,
    effectiveAgainstTags: [UNIT_TAGS.INFANTRY],
  },
  bruiser: {
    id: "bruiser",
    name: "Bruiser",
    family: UNIT_TAGS.VEHICLE,
    cost: 700,
    maxHealth: 24,
    attack: 14,
    armor: 7,
    movement: 5,
    minRange: 1,
    maxRange: 1,
    staminaMax: 5,
    ammoMax: 6,
    luck: 1,
    effectiveAgainstTags: [UNIT_TAGS.INFANTRY],
  },
  juggernaut: {
    id: "juggernaut",
    name: "Juggernaut",
    family: UNIT_TAGS.VEHICLE,
    cost: 2000,
    maxHealth: 28,
    attack: 17,
    armor: 12,
    movement: 4,
    minRange: 1,
    maxRange: 1,
    staminaMax: 4,
    ammoMax: 6,
    luck: 1,
    effectiveAgainstTags: [UNIT_TAGS.INFANTRY, UNIT_TAGS.VEHICLE],
  },
  medic: {
    id: "medic",
    name: "Medic",
    family: UNIT_TAGS.INFANTRY,
    cost: 500,
    maxHealth: 19,
    attack: 7,
    armor: 4,
    movement: 4,
    minRange: 1,
    maxRange: 1,
    staminaMax: 4,
    ammoMax: 7,
    luck: 2,
    effectiveAgainstTags: [],
  },
  mechanic: {
    id: "mechanic",
    name: "Mechanic",
    family: UNIT_TAGS.INFANTRY,
    cost: 600,
    maxHealth: 21,
    attack: 8,
    armor: 3,
    movement: 4,
    minRange: 1,
    maxRange: 1,
    staminaMax: 4,
    ammoMax: 7,
    luck: 2,
    effectiveAgainstTags: [],
  },
  "siege-gun": {
    id: "siege-gun",
    name: "Siege Gun",
    family: UNIT_TAGS.VEHICLE,
    cost: 600,
    maxHealth: 20,
    attack: 16,
    armor: 4,
    movement: 3,
    minRange: 2,
    maxRange: 3,
    staminaMax: 3,
    ammoMax: 6,
    luck: 1,
    effectiveAgainstTags: [UNIT_TAGS.VEHICLE],
  },
  skyguard: {
    id: "skyguard",
    name: "Skyguard",
    family: UNIT_TAGS.VEHICLE,
    cost: 500,
    maxHealth: 18,
    attack: 15,
    armor: 6,
    movement: 5,
    minRange: 1,
    maxRange: 2,
    staminaMax: 5,
    ammoMax: 6,
    luck: 2,
    effectiveAgainstTags: [UNIT_TAGS.AIR],
  },
  gunship: {
    id: "gunship",
    name: "Gunship",
    family: UNIT_TAGS.AIR,
    cost: 900,
    maxHealth: 18,
    attack: 13,
    armor: 2,
    movement: 7,
    minRange: 1,
    maxRange: 1,
    staminaMax: 7,
    ammoMax: 7,
    luck: 3,
    effectiveAgainstTags: [UNIT_TAGS.INFANTRY],
  },
  payload: {
    id: "payload",
    name: "Payload",
    family: UNIT_TAGS.AIR,
    cost: 2200,
    maxHealth: 20,
    attack: 19,
    armor: 4,
    movement: 6,
    minRange: 1,
    maxRange: 2,
    staminaMax: 6,
    ammoMax: 6,
    luck: 2,
    effectiveAgainstTags: [UNIT_TAGS.INFANTRY, UNIT_TAGS.VEHICLE],
  },
  interceptor: {
    id: "interceptor",
    name: "Interceptor",
    family: UNIT_TAGS.AIR,
    cost: 2000,
    maxHealth: 16,
    attack: 15,
    armor: 4,
    movement: 8,
    minRange: 1,
    maxRange: 1,
    staminaMax: 8,
    ammoMax: 7,
    luck: 3,
    effectiveAgainstTags: [UNIT_TAGS.AIR],
  },
  carrier: {
    id: "carrier",
    name: "Carrier",
    family: UNIT_TAGS.AIR,
    cost: 300,
    maxHealth: 24,
    attack: 0,
    armor: 2,
    movement: 5,
    minRange: 0,
    maxRange: 0,
    staminaMax: 5,
    ammoMax: 0,
    luck: 0,
    effectiveAgainstTags: [],
  },
};

export const BUILDING_RECRUITMENT = {
  barracks: ["grunt", "breaker", "longshot", "medic", "mechanic"],
  "motor-pool": ["runner", "bruiser", "juggernaut", "siege-gun", "skyguard"],
  airfield: ["gunship", "payload", "interceptor"],
};
